Repository auxfuse/hackathon-git-labs, pull requests merged in 2022-10, with the labels that each got.

#62 Update PR Template to include for Hacktoberfest 2022
  docs/pull_request_template.md
Labels: hacktoberfest-accepted

#63 Readme updates
  README.md
  basic.md
  docs/pull_request_template.md
  intermediate.md
Labels: documentation, hacktoberfest-accepted

#76 added my bio profile on json
  assets/data/community.json
Labels: invalid

#83 Alissa Landing Page
  community.json
  community/.DS_Store
  community/Alissa2/assets/css/style.css
  community/Alissa2/assets/js/script.js
  community/Alissa2/index.html
  community/Alissa2/main.html
  community/alyssa/style.css
Labels: hacktoberfest-accepted

#87 IreneN card
  assets/data/community.json
Labels: invalid, good first PR

#88 Add personal details to community JSON.
  assets/data/community.json
Labels: changes requested

#93 Added intermediate html
  intermediate.html
Labels: changes requested

#100 Andrius
  community/Andrius/andre-hackathon-2.png
  community/Andrius/index.html
  community/Andrius/style.css
Labels: hacktoberfest-accepted

#99 Random showcase
  assets/js/main.js
  index.html
Labels: hacktoberfest-accepted

#104 added my name to community.json
  assets/data/community.json
Labels: invalid, good first PR

#107 Added my own branch and my profile into the community.json.
  assets/data/community.json
Labels: invalid, good first PR

#105 Added breakpoints
  community/Andrius/style.css
Labels: hacktoberfest-accepted

#109 Abi's contribution
  assets/data/communitypages.json
  community/Abi/images/abi.jpg
  community/Abi/images/controller.jpg
  community/Abi/images/design.jpg
  community/Abi/images/f1.jpg
  community/Abi/images/octocat.png
  community/Abi/index.html
  community/Abi/style.css
Labels: hacktoberfest-accepted

#117 revert basic.md
  basic.html
Labels: invalid

#118 Added my piece using intermediate.md
  community/Vaibhav/img/github.png
  community/Vaibhav/img/instagram.png
  community/Vaibhav/img/link.png
  community/Vaibhav/img/twitter.png
  community/Vaibhav/index.html
  community/Vaibhav/style.css
Labels: hacktoberfest-accepted

#124 added my Profile card
  assets/data/community.json
  community/arioum/assets/background.png
  community/arioum/assets/profile.jpg
  community/arioum/index.html
  community/arioum/style.css
Labels: hacktoberfest-accepted

#122 Added sidebar component using HTML, CSS
  assets/data/community.json
  community/Shubham/index.html
  community/Shubham/style.css
Labels: question

#126 Update community.json
  assets/data/community.json
Labels: invalid

#108 jim contribution
  community/Jim/assets/css/style.css
  community/Jim/assets/images/land-rover.png
  community/Jim/assets/images/lynx.png
  community/Jim/index.html
Labels: changes requested

#134 Created a EmanuelGustafzon folder in the community folder together wi…
  community/EmanuelGustafzon/index.html
  community/EmanuelGustafzon/styles.css
Labels: hacktoberfest-accepted

#135 Add Navigation & Setup Slider for Skills Section
  community/Alissa2/README.md
  community/Alissa2/assets/css/style.css
  community/Alissa2/assets/images/alissa.png
  community/Alissa2/assets/images/bg4.jpeg
  community/Alissa2/assets/images/django.svg
  community/Alissa2/assets/images/mongodb.png
  community/Alissa2/index.html
  community/Alissa2/main.html
Labels: hacktoberfest-accepted, hacktoberfest

#136 Add JSON syntax check workflow
  .github/workflows/json-file-check.yml
  assets/data/community.json
  community/.DS_Store
  community/Alissa2/index.html
Labels: enhancement, hacktoberfest-accepted

#151 Intermediate pr
  community/Nicola/assets/css/style.css
  community/Nicola/assets/img/maze.jpeg
  community/Nicola/index.html
  community/Nicola/script.js
Labels: hacktoberfest-accepted

#154 sarah a. second pr
  community/Sarah A./index.html
  community/Sarah A./style.css
Labels: hacktoberfest-accepted

#160 update gallery page with slideshow and pics
  community/Aramantos/gallery.html
  community/Aramantos/index.html
  community/Aramantos/landscape/bmw-adventure.jpg
  community/Aramantos/portrait/bmw-gold.JPG
  community/Aramantos/portrait/honda.JPG
  community/Aramantos/portrait/young.JPG
  community/Aramantos/style.css
Labels: hacktoberfest-accepted

#166 Create Anya subfolder and initial custom creation
  assets/data/community.json
  community/Anya/index.html
  community/Anya/style.css
Labels: changes requested

#168 in progress pagination code
  assets/js/main.js
  index.html
Labels: changes requested

#176 created privacy.html, created privacy.css and styled html page to mat…
  assets/css/style.css
  privacy.html
Labels: changes requested

#178 Created accessibility.html page
  accessibility.html
  assets/css/style.css
  privacy.html
Labels: hacktoberfest-accepted

#179 added name in community.json
  assets/data/community.json
Labels: good first PR

#183 Added identification details to community.json
  assets/data/community.json
  beratzorlu
  community/beratzorlu/index.html
  community/beratzorlu/pumpking_scary.jpg
  community/beratzorlu/style.css
Labels: good first PR
